# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impedance.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImpedanceApp(object):
    def setupUi(self, ImpedanceApp):
        ImpedanceApp.setObjectName("ImpedanceApp")
        ImpedanceApp.resize(1208, 891)
        ImpedanceApp.setMinimumSize(QtCore.QSize(1119, 730))
        self.centralwidget = QtWidgets.QWidget(ImpedanceApp)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frequencyBox = QtWidgets.QGroupBox(self.centralwidget)
        self.frequencyBox.setMaximumSize(QtCore.QSize(261, 16777215))
        self.frequencyBox.setObjectName("frequencyBox")
        self.gridLayout = QtWidgets.QGridLayout(self.frequencyBox)
        self.gridLayout.setObjectName("gridLayout")
        self.startFreqUnit = QtWidgets.QComboBox(self.frequencyBox)
        self.startFreqUnit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.startFreqUnit.setObjectName("startFreqUnit")
        self.startFreqUnit.addItem("")
        self.startFreqUnit.addItem("")
        self.startFreqUnit.addItem("")
        self.gridLayout.addWidget(self.startFreqUnit, 2, 2, 1, 1)
        self.startFrequencyLabel = QtWidgets.QLabel(self.frequencyBox)
        self.startFrequencyLabel.setObjectName("startFrequencyLabel")
        self.gridLayout.addWidget(self.startFrequencyLabel, 2, 0, 1, 1)
        self.startFreq = QtWidgets.QDoubleSpinBox(self.frequencyBox)
        self.startFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.startFreq.setDecimals(0)
        self.startFreq.setMinimum(20.0)
        self.startFreq.setMaximum(10000000.0)
        self.startFreq.setProperty("value", 20.0)
        self.startFreq.setObjectName("startFreq")
        self.gridLayout.addWidget(self.startFreq, 2, 1, 1, 1)
        self.stopFreqUnit = QtWidgets.QComboBox(self.frequencyBox)
        self.stopFreqUnit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.stopFreqUnit.setObjectName("stopFreqUnit")
        self.stopFreqUnit.addItem("")
        self.stopFreqUnit.addItem("")
        self.stopFreqUnit.addItem("")
        self.gridLayout.addWidget(self.stopFreqUnit, 3, 2, 1, 1)
        self.stopFrequencyLabel = QtWidgets.QLabel(self.frequencyBox)
        self.stopFrequencyLabel.setObjectName("stopFrequencyLabel")
        self.gridLayout.addWidget(self.stopFrequencyLabel, 3, 0, 1, 1)
        self.stopFreq = QtWidgets.QDoubleSpinBox(self.frequencyBox)
        self.stopFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.stopFreq.setDecimals(0)
        self.stopFreq.setMinimum(1.0)
        self.stopFreq.setMaximum(10.0)
        self.stopFreq.setProperty("value", 10.0)
        self.stopFreq.setObjectName("stopFreq")
        self.gridLayout.addWidget(self.stopFreq, 3, 1, 1, 1)
        self.fixedFreqUnit = QtWidgets.QComboBox(self.frequencyBox)
        self.fixedFreqUnit.setEnabled(False)
        self.fixedFreqUnit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fixedFreqUnit.setObjectName("fixedFreqUnit")
        self.fixedFreqUnit.addItem("")
        self.fixedFreqUnit.addItem("")
        self.fixedFreqUnit.addItem("")
        self.gridLayout.addWidget(self.fixedFreqUnit, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pointSpacingLabel = QtWidgets.QLabel(self.frequencyBox)
        self.pointSpacingLabel.setObjectName("pointSpacingLabel")
        self.horizontalLayout_2.addWidget(self.pointSpacingLabel)
        self.spacingType = QtWidgets.QComboBox(self.frequencyBox)
        self.spacingType.setMaximumSize(QtCore.QSize(50000, 16777215))
        self.spacingType.setObjectName("spacingType")
        self.spacingType.addItem("")
        self.spacingType.addItem("")
        self.spacingType.addItem("")
        self.horizontalLayout_2.addWidget(self.spacingType)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 3)
        self.fixFreq = QtWidgets.QCheckBox(self.frequencyBox)
        self.fixFreq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fixFreq.setStyleSheet("font-size:10pt; font-weight:600;")
        self.fixFreq.setTristate(False)
        self.fixFreq.setObjectName("fixFreq")
        self.gridLayout.addWidget(self.fixFreq, 0, 0, 1, 1)
        self.fixedFreq = QtWidgets.QDoubleSpinBox(self.frequencyBox)
        self.fixedFreq.setEnabled(False)
        self.fixedFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.fixedFreq.setDecimals(0)
        self.fixedFreq.setMinimum(1.0)
        self.fixedFreq.setMaximum(10000.0)
        self.fixedFreq.setProperty("value", 1.0)
        self.fixedFreq.setObjectName("fixedFreq")
        self.gridLayout.addWidget(self.fixedFreq, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pointsLabel = QtWidgets.QLabel(self.frequencyBox)
        self.pointsLabel.setObjectName("pointsLabel")
        self.horizontalLayout_3.addWidget(self.pointsLabel)
        self.npoints = QtWidgets.QSpinBox(self.frequencyBox)
        self.npoints.setMaximumSize(QtCore.QSize(50000, 16777215))
        self.npoints.setAlignment(QtCore.Qt.AlignCenter)
        self.npoints.setMinimum(1)
        self.npoints.setMaximum(500)
        self.npoints.setProperty("value", 20)
        self.npoints.setObjectName("npoints")
        self.horizontalLayout_3.addWidget(self.npoints)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 3)
        self.gridLayout_10.addWidget(self.frequencyBox, 0, 0, 1, 1)
        self.ImpdPlot = PlotWidget(self.centralwidget)
        self.ImpdPlot.setMinimumSize(QtCore.QSize(0, 0))
        self.ImpdPlot.setObjectName("ImpdPlot")
        self.gridLayout_10.addWidget(self.ImpdPlot, 0, 1, 4, 2)
        self.voltageBox = QtWidgets.QGroupBox(self.centralwidget)
        self.voltageBox.setMinimumSize(QtCore.QSize(0, 240))
        self.voltageBox.setObjectName("voltageBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.voltageBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.acVoltage = QtWidgets.QLabel(self.voltageBox)
        self.acVoltage.setObjectName("acVoltage")
        self.gridLayout_8.addWidget(self.acVoltage, 0, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.voltageBox)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMinimum(0.005)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.001)
        self.doubleSpinBox.setProperty("value", 0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_8.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.DCvoltageBox = QtWidgets.QGroupBox(self.voltageBox)
        self.DCvoltageBox.setCheckable(True)
        self.DCvoltageBox.setChecked(False)
        self.DCvoltageBox.setObjectName("DCvoltageBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.DCvoltageBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.fixedDCvolt = QtWidgets.QDoubleSpinBox(self.DCvoltageBox)
        self.fixedDCvolt.setAlignment(QtCore.Qt.AlignCenter)
        self.fixedDCvolt.setDecimals(3)
        self.fixedDCvolt.setMinimum(-40.0)
        self.fixedDCvolt.setMaximum(40.0)
        self.fixedDCvolt.setSingleStep(0.1)
        self.fixedDCvolt.setObjectName("fixedDCvolt")
        self.gridLayout_7.addWidget(self.fixedDCvolt, 0, 1, 1, 2)
        self.voltagePointsLabel = QtWidgets.QLabel(self.DCvoltageBox)
        self.voltagePointsLabel.setEnabled(False)
        self.voltagePointsLabel.setObjectName("voltagePointsLabel")
        self.gridLayout_7.addWidget(self.voltagePointsLabel, 5, 0, 1, 2)
        self.fixDCvolts = QtWidgets.QCheckBox(self.DCvoltageBox)
        self.fixDCvolts.setStyleSheet("font-size:10pt; font-weight:600;")
        self.fixDCvolts.setChecked(True)
        self.fixDCvolts.setObjectName("fixDCvolts")
        self.gridLayout_7.addWidget(self.fixDCvolts, 0, 0, 1, 1)
        self.voltageNpoints = QtWidgets.QSpinBox(self.DCvoltageBox)
        self.voltageNpoints.setEnabled(False)
        self.voltageNpoints.setMaximumSize(QtCore.QSize(50000, 16777215))
        self.voltageNpoints.setAlignment(QtCore.Qt.AlignCenter)
        self.voltageNpoints.setMinimum(1)
        self.voltageNpoints.setMaximum(500)
        self.voltageNpoints.setProperty("value", 20)
        self.voltageNpoints.setObjectName("voltageNpoints")
        self.gridLayout_7.addWidget(self.voltageNpoints, 5, 2, 1, 1)
        self.traceback = QtWidgets.QCheckBox(self.DCvoltageBox)
        self.traceback.setEnabled(False)
        self.traceback.setStyleSheet("font-size:10pt; font-weight:600;")
        self.traceback.setObjectName("traceback")
        self.gridLayout_7.addWidget(self.traceback, 6, 0, 1, 3)
        self.voltageNcyclesLabel = QtWidgets.QLabel(self.DCvoltageBox)
        self.voltageNcyclesLabel.setEnabled(False)
        self.voltageNcyclesLabel.setObjectName("voltageNcyclesLabel")
        self.gridLayout_7.addWidget(self.voltageNcyclesLabel, 7, 0, 1, 2)
        self.Vncycles = QtWidgets.QSpinBox(self.DCvoltageBox)
        self.Vncycles.setEnabled(False)
        self.Vncycles.setMaximumSize(QtCore.QSize(50000, 16777215))
        self.Vncycles.setAlignment(QtCore.Qt.AlignCenter)
        self.Vncycles.setMinimum(1)
        self.Vncycles.setMaximum(500)
        self.Vncycles.setProperty("value", 1)
        self.Vncycles.setObjectName("Vncycles")
        self.gridLayout_7.addWidget(self.Vncycles, 7, 2, 1, 1)
        self.stopVoltageLabel = QtWidgets.QLabel(self.DCvoltageBox)
        self.stopVoltageLabel.setEnabled(False)
        self.stopVoltageLabel.setObjectName("stopVoltageLabel")
        self.gridLayout_7.addWidget(self.stopVoltageLabel, 3, 0, 2, 2)
        self.startVoltageLabel = QtWidgets.QLabel(self.DCvoltageBox)
        self.startVoltageLabel.setEnabled(False)
        self.startVoltageLabel.setObjectName("startVoltageLabel")
        self.gridLayout_7.addWidget(self.startVoltageLabel, 1, 0, 2, 2)
        self.startVoltage = QtWidgets.QDoubleSpinBox(self.DCvoltageBox)
        self.startVoltage.setEnabled(False)
        self.startVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.startVoltage.setDecimals(3)
        self.startVoltage.setMinimum(-40.0)
        self.startVoltage.setMaximum(40.0)
        self.startVoltage.setSingleStep(0.1)
        self.startVoltage.setProperty("value", -1.0)
        self.startVoltage.setObjectName("startVoltage")
        self.gridLayout_7.addWidget(self.startVoltage, 2, 2, 1, 1)
        self.stopVoltage = QtWidgets.QDoubleSpinBox(self.DCvoltageBox)
        self.stopVoltage.setEnabled(False)
        self.stopVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.stopVoltage.setDecimals(3)
        self.stopVoltage.setMinimum(-40.0)
        self.stopVoltage.setMaximum(40.0)
        self.stopVoltage.setSingleStep(0.1)
        self.stopVoltage.setProperty("value", 1.0)
        self.stopVoltage.setObjectName("stopVoltage")
        self.gridLayout_7.addWidget(self.stopVoltage, 4, 2, 1, 1)
        self.gridLayout_8.addWidget(self.DCvoltageBox, 1, 0, 1, 2)
        self.gridLayout_10.addWidget(self.voltageBox, 1, 0, 1, 1)
        self.statusBox = QtWidgets.QGroupBox(self.centralwidget)
        self.statusBox.setMaximumSize(QtCore.QSize(390, 16777215))
        self.statusBox.setObjectName("statusBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.statusBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.impedanceReStatusLabel = QtWidgets.QLabel(self.statusBox)
        self.impedanceReStatusLabel.setObjectName("impedanceReStatusLabel")
        self.gridLayout_5.addWidget(self.impedanceReStatusLabel, 2, 0, 1, 1)
        self.temperatureStatusLabel = QtWidgets.QLabel(self.statusBox)
        self.temperatureStatusLabel.setObjectName("temperatureStatusLabel")
        self.gridLayout_5.addWidget(self.temperatureStatusLabel, 0, 4, 1, 1)
        self.capacitanceStatusLabel = QtWidgets.QLabel(self.statusBox)
        self.capacitanceStatusLabel.setObjectName("capacitanceStatusLabel")
        self.gridLayout_5.addWidget(self.capacitanceStatusLabel, 3, 0, 1, 1)
        self.tandstatusLabel = QtWidgets.QLabel(self.statusBox)
        self.tandstatusLabel.setObjectName("tandstatusLabel")
        self.gridLayout_5.addWidget(self.tandstatusLabel, 3, 4, 1, 1)
        self.tandStatus = QtWidgets.QLineEdit(self.statusBox)
        self.tandStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.tandStatus.setPalette(palette)
        self.tandStatus.setStyleSheet("font: 11pt;")
        self.tandStatus.setObjectName("tandStatus")
        self.gridLayout_5.addWidget(self.tandStatus, 3, 5, 1, 1)
        self.capStatus = QtWidgets.QLineEdit(self.statusBox)
        self.capStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.capStatus.setPalette(palette)
        self.capStatus.setStyleSheet("font: 11pt;")
        self.capStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.capStatus.setObjectName("capStatus")
        self.gridLayout_5.addWidget(self.capStatus, 3, 1, 1, 1)
        self.frequencyStatusLabel = QtWidgets.QLabel(self.statusBox)
        self.frequencyStatusLabel.setObjectName("frequencyStatusLabel")
        self.gridLayout_5.addWidget(self.frequencyStatusLabel, 0, 0, 1, 1)
        self.impedanceImStatusLabel = QtWidgets.QLabel(self.statusBox)
        self.impedanceImStatusLabel.setObjectName("impedanceImStatusLabel")
        self.gridLayout_5.addWidget(self.impedanceImStatusLabel, 2, 4, 1, 1)
        self.tempStatus = QtWidgets.QLineEdit(self.statusBox)
        self.tempStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.tempStatus.setPalette(palette)
        self.tempStatus.setStyleSheet("font: 11pt;")
        self.tempStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempStatus.setObjectName("tempStatus")
        self.gridLayout_5.addWidget(self.tempStatus, 0, 5, 1, 1)
        self.line = QtWidgets.QFrame(self.statusBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 0, 3, 4, 1)
        self.ZReStatus = QtWidgets.QLineEdit(self.statusBox)
        self.ZReStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.ZReStatus.setPalette(palette)
        self.ZReStatus.setStyleSheet("font: 11pt;")
        self.ZReStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ZReStatus.setObjectName("ZReStatus")
        self.gridLayout_5.addWidget(self.ZReStatus, 2, 1, 1, 1)
        self.sampleIDLabel = QtWidgets.QLabel(self.statusBox)
        self.sampleIDLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleIDLabel.setObjectName("sampleIDLabel")
        self.gridLayout_5.addWidget(self.sampleIDLabel, 4, 0, 1, 2)
        self.ZImStatus = QtWidgets.QLineEdit(self.statusBox)
        self.ZImStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.ZImStatus.setPalette(palette)
        self.ZImStatus.setStyleSheet("font: 11pt;")
        self.ZImStatus.setObjectName("ZImStatus")
        self.gridLayout_5.addWidget(self.ZImStatus, 2, 5, 1, 1)
        self.freqStatus = QtWidgets.QLineEdit(self.statusBox)
        self.freqStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.freqStatus.setPalette(palette)
        self.freqStatus.setStyleSheet("font: 11pt;")
        self.freqStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.freqStatus.setObjectName("freqStatus")
        self.gridLayout_5.addWidget(self.freqStatus, 0, 1, 1, 1)
        self.sampleStatusLabel = QtWidgets.QLabel(self.statusBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 115, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 115, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.sampleStatusLabel.setPalette(palette)
        self.sampleStatusLabel.setObjectName("sampleStatusLabel")
        self.gridLayout_5.addWidget(self.sampleStatusLabel, 4, 4, 1, 2)
        self.ACvoltStatusLabel = QtWidgets.QLabel(self.statusBox)
        self.ACvoltStatusLabel.setObjectName("ACvoltStatusLabel")
        self.gridLayout_5.addWidget(self.ACvoltStatusLabel, 1, 0, 1, 1)
        self.ACvoltStatus = QtWidgets.QLineEdit(self.statusBox)
        self.ACvoltStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.ACvoltStatus.setPalette(palette)
        self.ACvoltStatus.setStyleSheet("font: 11pt;")
        self.ACvoltStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ACvoltStatus.setObjectName("ACvoltStatus")
        self.gridLayout_5.addWidget(self.ACvoltStatus, 1, 1, 1, 1)
        self.DCvoltStatusLabel = QtWidgets.QLabel(self.statusBox)
        self.DCvoltStatusLabel.setObjectName("DCvoltStatusLabel")
        self.gridLayout_5.addWidget(self.DCvoltStatusLabel, 1, 4, 1, 1)
        self.DCvoltStatus = QtWidgets.QLineEdit(self.statusBox)
        self.DCvoltStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.DCvoltStatus.setPalette(palette)
        self.DCvoltStatus.setStyleSheet("font: 11pt;")
        self.DCvoltStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DCvoltStatus.setObjectName("DCvoltStatus")
        self.gridLayout_5.addWidget(self.DCvoltStatus, 1, 5, 1, 1)
        self.gridLayout_10.addWidget(self.statusBox, 4, 1, 2, 1)
        self.plotBox = QtWidgets.QGroupBox(self.centralwidget)
        self.plotBox.setObjectName("plotBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.plotBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.xaxisBox = QtWidgets.QGroupBox(self.plotBox)
        self.xaxisBox.setMinimumSize(QtCore.QSize(0, 0))
        self.xaxisBox.setObjectName("xaxisBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.xaxisBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.xaxisTemp = QtWidgets.QPushButton(self.xaxisBox)
        self.xaxisTemp.setObjectName("xaxisTemp")
        self.gridLayout_6.addWidget(self.xaxisTemp, 0, 0, 1, 1)
        self.xaxisFreq = QtWidgets.QPushButton(self.xaxisBox)
        self.xaxisFreq.setObjectName("xaxisFreq")
        self.gridLayout_6.addWidget(self.xaxisFreq, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.xaxisBox)
        self.yaxisBox = QtWidgets.QGroupBox(self.plotBox)
        self.yaxisBox.setMinimumSize(QtCore.QSize(0, 0))
        self.yaxisBox.setObjectName("yaxisBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.yaxisBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.impedanceButton = QtWidgets.QPushButton(self.yaxisBox)
        self.impedanceButton.setCheckable(True)
        self.impedanceButton.setObjectName("impedanceButton")
        self.gridLayout_9.addWidget(self.impedanceButton, 0, 0, 1, 1)
        self.resistanceButton = QtWidgets.QPushButton(self.yaxisBox)
        self.resistanceButton.setCheckable(True)
        self.resistanceButton.setObjectName("resistanceButton")
        self.gridLayout_9.addWidget(self.resistanceButton, 0, 1, 1, 1)
        self.inductanceButton = QtWidgets.QPushButton(self.yaxisBox)
        self.inductanceButton.setCheckable(True)
        self.inductanceButton.setObjectName("inductanceButton")
        self.gridLayout_9.addWidget(self.inductanceButton, 1, 1, 1, 1)
        self.capacitanceButton = QtWidgets.QPushButton(self.yaxisBox)
        self.capacitanceButton.setCheckable(True)
        self.capacitanceButton.setObjectName("capacitanceButton")
        self.gridLayout_9.addWidget(self.capacitanceButton, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.yaxisBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.scaleBox = QtWidgets.QGroupBox(self.plotBox)
        self.scaleBox.setMinimumSize(QtCore.QSize(0, 0))
        self.scaleBox.setObjectName("scaleBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scaleBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.autoScaleButton = QtWidgets.QPushButton(self.scaleBox)
        self.autoScaleButton.setCheckable(True)
        self.autoScaleButton.setObjectName("autoScaleButton")
        self.verticalLayout.addWidget(self.autoScaleButton)
        self.xaxisScale = QtWidgets.QPushButton(self.scaleBox)
        self.xaxisScale.setObjectName("xaxisScale")
        self.verticalLayout.addWidget(self.xaxisScale)
        self.yaxisScale = QtWidgets.QPushButton(self.scaleBox)
        self.yaxisScale.setObjectName("yaxisScale")
        self.verticalLayout.addWidget(self.yaxisScale)
        self.horizontalLayout_5.addWidget(self.scaleBox)
        self.gridLayout_10.addWidget(self.plotBox, 4, 2, 2, 1)
        self.measureControlBox = QtWidgets.QGroupBox(self.centralwidget)
        self.measureControlBox.setMinimumSize(QtCore.QSize(120, 0))
        self.measureControlBox.setMaximumSize(QtCore.QSize(500, 120))
        self.measureControlBox.setObjectName("measureControlBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.measureControlBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.startButton = QtWidgets.QPushButton(self.measureControlBox)
        self.startButton.setMinimumSize(QtCore.QSize(0, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.startButton.setPalette(palette)
        self.startButton.setStyleSheet("background-color: rgb(230, 255, 254)")
        self.startButton.setObjectName("startButton")
        self.gridLayout_4.addWidget(self.startButton, 0, 1, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.measureControlBox)
        self.stopButton.setMinimumSize(QtCore.QSize(0, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.stopButton.setPalette(palette)
        self.stopButton.setStyleSheet("background-color: rgb(255, 231, 210)")
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_4.addWidget(self.stopButton, 0, 2, 1, 1)
        self.gridLayout_10.addWidget(self.measureControlBox, 5, 0, 1, 1)
        self.fileBox = QtWidgets.QGroupBox(self.centralwidget)
        self.fileBox.setMinimumSize(QtCore.QSize(0, 100))
        self.fileBox.setMaximumSize(QtCore.QSize(261, 16777215))
        self.fileBox.setObjectName("fileBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fileBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.saveParamButton = QtWidgets.QPushButton(self.fileBox)
        self.saveParamButton.setObjectName("saveParamButton")
        self.gridLayout_3.addWidget(self.saveParamButton, 1, 1, 1, 1)
        self.loadParamButton = QtWidgets.QPushButton(self.fileBox)
        self.loadParamButton.setObjectName("loadParamButton")
        self.gridLayout_3.addWidget(self.loadParamButton, 1, 0, 1, 1)
        self.filenameText = QtWidgets.QLineEdit(self.fileBox)
        self.filenameText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filenameText.setObjectName("filenameText")
        self.gridLayout_3.addWidget(self.filenameText, 0, 1, 1, 1)
        self.saveFilenameLabel = QtWidgets.QLabel(self.fileBox)
        self.saveFilenameLabel.setObjectName("saveFilenameLabel")
        self.gridLayout_3.addWidget(self.saveFilenameLabel, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.fileBox, 4, 0, 1, 1)
        self.temperatureBox = QtWidgets.QGroupBox(self.centralwidget)
        self.temperatureBox.setMaximumSize(QtCore.QSize(261, 300))
        self.temperatureBox.setCheckable(True)
        self.temperatureBox.setObjectName("temperatureBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.temperatureBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.temperatureBox)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.measureLabel = QtWidgets.QLabel(self.frame)
        self.measureLabel.setEnabled(True)
        self.measureLabel.setObjectName("measureLabel")
        self.horizontalLayout.addWidget(self.measureLabel)
        self.tempInterval = QtWidgets.QSpinBox(self.frame)
        self.tempInterval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempInterval.setMinimum(1)
        self.tempInterval.setMaximum(100)
        self.tempInterval.setProperty("value", 5)
        self.tempInterval.setObjectName("tempInterval")
        self.horizontalLayout.addWidget(self.tempInterval)
        self.degreesLabel = QtWidgets.QLabel(self.frame)
        self.degreesLabel.setObjectName("degreesLabel")
        self.horizontalLayout.addWidget(self.degreesLabel)
        self.gridLayout_2.addWidget(self.frame, 7, 0, 1, 2)
        self.loadTempButton = QtWidgets.QPushButton(self.temperatureBox)
        self.loadTempButton.setObjectName("loadTempButton")
        self.gridLayout_2.addWidget(self.loadTempButton, 8, 0, 1, 2)
        self.tempControllerLabel = QtWidgets.QLabel(self.temperatureBox)
        self.tempControllerLabel.setObjectName("tempControllerLabel")
        self.gridLayout_2.addWidget(self.tempControllerLabel, 2, 0, 1, 1)
        self.inst = QtWidgets.QComboBox(self.temperatureBox)
        self.inst.setObjectName("inst")
        self.inst.addItem("")
        self.inst.addItem("")
        self.gridLayout_2.addWidget(self.inst, 2, 1, 1, 1)
        self.measureMode = QtWidgets.QComboBox(self.temperatureBox)
        self.measureMode.setObjectName("measureMode")
        self.measureMode.addItem("")
        self.measureMode.addItem("")
        self.measureMode.addItem("")
        self.gridLayout_2.addWidget(self.measureMode, 5, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fixTemp = QtWidgets.QCheckBox(self.temperatureBox)
        self.fixTemp.setStyleSheet("font-size:10pt; font-weight:600;")
        self.fixTemp.setObjectName("fixTemp")
        self.horizontalLayout_4.addWidget(self.fixTemp)
        self.fixedTemp = QtWidgets.QDoubleSpinBox(self.temperatureBox)
        self.fixedTemp.setEnabled(False)
        self.fixedTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.fixedTemp.setMinimum(10.0)
        self.fixedTemp.setMaximum(600.0)
        self.fixedTemp.setProperty("value", 300.0)
        self.fixedTemp.setObjectName("fixedTemp")
        self.horizontalLayout_4.addWidget(self.fixedTemp)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 2)
        self.modeLabel = QtWidgets.QLabel(self.temperatureBox)
        self.modeLabel.setObjectName("modeLabel")
        self.gridLayout_2.addWidget(self.modeLabel, 5, 0, 1, 1)
        self.stopTemperatureLabel = QtWidgets.QLabel(self.temperatureBox)
        self.stopTemperatureLabel.setObjectName("stopTemperatureLabel")
        self.gridLayout_2.addWidget(self.stopTemperatureLabel, 4, 0, 1, 1)
        self.stopTemp = QtWidgets.QDoubleSpinBox(self.temperatureBox)
        self.stopTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.stopTemp.setMinimum(10.0)
        self.stopTemp.setMaximum(600.0)
        self.stopTemp.setObjectName("stopTemp")
        self.gridLayout_2.addWidget(self.stopTemp, 4, 1, 1, 1)
        self.startTemperatureLabel = QtWidgets.QLabel(self.temperatureBox)
        self.startTemperatureLabel.setObjectName("startTemperatureLabel")
        self.gridLayout_2.addWidget(self.startTemperatureLabel, 3, 0, 1, 1)
        self.startTemp = QtWidgets.QDoubleSpinBox(self.temperatureBox)
        self.startTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.startTemp.setMinimum(10.0)
        self.startTemp.setMaximum(600.0)
        self.startTemp.setProperty("value", 300.0)
        self.startTemp.setObjectName("startTemp")
        self.gridLayout_2.addWidget(self.startTemp, 3, 1, 1, 1)
        self.gridLayout_10.addWidget(self.temperatureBox, 2, 0, 2, 1)
        ImpedanceApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImpedanceApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1208, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        ImpedanceApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImpedanceApp)
        self.statusbar.setObjectName("statusbar")
        ImpedanceApp.setStatusBar(self.statusbar)
        self.actionMeasurement = QtWidgets.QAction(ImpedanceApp)
        self.actionMeasurement.setObjectName("actionMeasurement")
        self.actionAC_Voltage = QtWidgets.QAction(ImpedanceApp)
        self.actionAC_Voltage.setObjectName("actionAC_Voltage")
        self.actionAC_Current = QtWidgets.QAction(ImpedanceApp)
        self.actionAC_Current.setObjectName("actionAC_Current")
        self.actionDC_Current = QtWidgets.QAction(ImpedanceApp)
        self.actionDC_Current.setObjectName("actionDC_Current")
        self.actionCalibration = QtWidgets.QAction(ImpedanceApp)
        self.actionCalibration.setObjectName("actionCalibration")
        self.actionExit = QtWidgets.QAction(ImpedanceApp)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionMeasurement)
        self.menuOptions.addAction(self.actionAC_Voltage)
        self.menuOptions.addAction(self.actionAC_Current)
        self.menuOptions.addAction(self.actionDC_Current)
        self.menuOptions.addAction(self.actionCalibration)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(ImpedanceApp)
        self.stopFreqUnit.setCurrentIndex(2)
        self.fixedFreqUnit.setCurrentIndex(1)
        self.spacingType.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ImpedanceApp)

    def retranslateUi(self, ImpedanceApp):
        _translate = QtCore.QCoreApplication.translate
        ImpedanceApp.setWindowTitle(_translate("ImpedanceApp", "Impedance Measurement"))
        self.frequencyBox.setTitle(_translate("ImpedanceApp", "Frequency Sweep"))
        self.startFreqUnit.setItemText(0, _translate("ImpedanceApp", "Hz"))
        self.startFreqUnit.setItemText(1, _translate("ImpedanceApp", "kHz"))
        self.startFreqUnit.setItemText(2, _translate("ImpedanceApp", "MHz"))
        self.startFrequencyLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Start</span></p></body></html>"))
        self.stopFreqUnit.setItemText(0, _translate("ImpedanceApp", "Hz"))
        self.stopFreqUnit.setItemText(1, _translate("ImpedanceApp", "kHz"))
        self.stopFreqUnit.setItemText(2, _translate("ImpedanceApp", "MHz"))
        self.stopFrequencyLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Stop</span></p></body></html>"))
        self.fixedFreqUnit.setItemText(0, _translate("ImpedanceApp", "Hz"))
        self.fixedFreqUnit.setItemText(1, _translate("ImpedanceApp", "kHz"))
        self.fixedFreqUnit.setItemText(2, _translate("ImpedanceApp", "MHz"))
        self.pointSpacingLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Point spacing</span></p></body></html>"))
        self.spacingType.setItemText(0, _translate("ImpedanceApp", "Linear"))
        self.spacingType.setItemText(1, _translate("ImpedanceApp", "Logarithm"))
        self.spacingType.setItemText(2, _translate("ImpedanceApp", "Linear-Log"))
        self.fixFreq.setText(_translate("ImpedanceApp", "Fix Frequency"))
        self.pointsLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Number of points</span></p></body></html>"))
        self.voltageBox.setTitle(_translate("ImpedanceApp", "Voltage"))
        self.acVoltage.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">AC Voltage (V<sub>rms</sub>)</span></p></body></html>"))
        self.DCvoltageBox.setTitle(_translate("ImpedanceApp", "DC Bias Sweep"))
        self.voltagePointsLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Number of points</span></p></body></html>"))
        self.fixDCvolts.setText(_translate("ImpedanceApp", "Fix DC Bias"))
        self.traceback.setToolTip(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:400;\">Trace back to the starting voltage in same way. You can also set number of cycles to trace.</span></p></body></html>"))
        self.traceback.setText(_translate("ImpedanceApp", "Traceback"))
        self.voltageNcyclesLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Number of cycles</span></p></body></html>"))
        self.stopVoltageLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Stop (V)</span></p></body></html>"))
        self.startVoltageLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Start (V)</span></p></body></html>"))
        self.statusBox.setTitle(_translate("ImpedanceApp", "Current Status"))
        self.impedanceReStatusLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Z\' (Re)</span></p></body></html>"))
        self.temperatureStatusLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Temperature</span></p></body></html>"))
        self.capacitanceStatusLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Capacitance</span></p></body></html>"))
        self.tandstatusLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">tan(δ)</span></p></body></html>"))
        self.capStatus.setText(_translate("ImpedanceApp", "F"))
        self.frequencyStatusLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Frequency</span></p></body></html>"))
        self.impedanceImStatusLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Z\'\' (Im)</span></p></body></html>"))
        self.tempStatus.setText(_translate("ImpedanceApp", "°C"))
        self.ZReStatus.setText(_translate("ImpedanceApp", "Ω"))
        self.sampleIDLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Sample ID:</span></p></body></html>"))
        self.freqStatus.setText(_translate("ImpedanceApp", "Hz"))
        self.sampleStatusLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">CryoChamber 1</span></p></body></html>"))
        self.ACvoltStatusLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">AC Voltage</span></p></body></html>"))
        self.ACvoltStatus.setText(_translate("ImpedanceApp", "V"))
        self.DCvoltStatusLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">DC Bias</span></p></body></html>"))
        self.DCvoltStatus.setText(_translate("ImpedanceApp", "V"))
        self.plotBox.setTitle(_translate("ImpedanceApp", "Plot"))
        self.xaxisBox.setTitle(_translate("ImpedanceApp", "X-Axis"))
        self.xaxisTemp.setText(_translate("ImpedanceApp", "Temperature"))
        self.xaxisFreq.setText(_translate("ImpedanceApp", "Frequency"))
        self.yaxisBox.setTitle(_translate("ImpedanceApp", "Y-Axis"))
        self.impedanceButton.setText(_translate("ImpedanceApp", "Impedance"))
        self.resistanceButton.setText(_translate("ImpedanceApp", "Resistance"))
        self.inductanceButton.setText(_translate("ImpedanceApp", "Inductance"))
        self.capacitanceButton.setText(_translate("ImpedanceApp", "Capacitance"))
        self.scaleBox.setTitle(_translate("ImpedanceApp", "Scale"))
        self.autoScaleButton.setText(_translate("ImpedanceApp", "Auto"))
        self.xaxisScale.setText(_translate("ImpedanceApp", "X-Axis"))
        self.yaxisScale.setText(_translate("ImpedanceApp", "Y-Axis"))
        self.measureControlBox.setTitle(_translate("ImpedanceApp", "Measurement"))
        self.startButton.setText(_translate("ImpedanceApp", "Start"))
        self.stopButton.setText(_translate("ImpedanceApp", "Stop"))
        self.fileBox.setTitle(_translate("ImpedanceApp", "File"))
        self.saveParamButton.setText(_translate("ImpedanceApp", "Save Parameters"))
        self.loadParamButton.setText(_translate("ImpedanceApp", "Load Parameters"))
        self.filenameText.setText(_translate("ImpedanceApp", "sample1.csv"))
        self.saveFilenameLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Save Filename</span></p></body></html>"))
        self.temperatureBox.setTitle(_translate("ImpedanceApp", "Temperature Scan"))
        self.measureLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:10pt;\">Measure every</span></p></body></html>"))
        self.degreesLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:10pt;\">degrees</span></p></body></html>"))
        self.loadTempButton.setToolTip(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt;\">Text file containing one temperature (°C) point in each line, no other text. Preferably in ascending or descending order, but not necessary.</span></p></body></html>"))
        self.loadTempButton.setText(_translate("ImpedanceApp", "Choose Custom Temperature Points"))
        self.tempControllerLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Controller</span></p></body></html>"))
        self.inst.setItemText(0, _translate("ImpedanceApp", "Chino"))
        self.inst.setItemText(1, _translate("ImpedanceApp", "Linkam"))
        self.measureMode.setItemText(0, _translate("ImpedanceApp", "Continuous"))
        self.measureMode.setItemText(1, _translate("ImpedanceApp", "Specify Interval"))
        self.measureMode.setItemText(2, _translate("ImpedanceApp", "Load from file"))
        self.fixTemp.setText(_translate("ImpedanceApp", "Fix Temperature (K)"))
        self.modeLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Mode</span></p></body></html>"))
        self.stopTemperatureLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Stop (K)</span></p></body></html>"))
        self.startTemperatureLabel.setText(_translate("ImpedanceApp", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Start (K)</span></p></body></html>"))
        self.menuFile.setTitle(_translate("ImpedanceApp", "File"))
        self.menuOptions.setTitle(_translate("ImpedanceApp", "Advance Settings"))
        self.actionMeasurement.setText(_translate("ImpedanceApp", "Measurement"))
        self.actionAC_Voltage.setText(_translate("ImpedanceApp", "AC Voltage"))
        self.actionAC_Current.setText(_translate("ImpedanceApp", "AC Current"))
        self.actionDC_Current.setText(_translate("ImpedanceApp", "DC Current"))
        self.actionCalibration.setText(_translate("ImpedanceApp", "Calibration"))
        self.actionExit.setText(_translate("ImpedanceApp", "Exit"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImpedanceApp = QtWidgets.QMainWindow()
    ui = Ui_ImpedanceApp()
    ui.setupUi(ImpedanceApp)
    ImpedanceApp.show()
    sys.exit(app.exec_())

