# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impedance.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 730)
        MainWindow.setMinimumSize(QtCore.QSize(1119, 730))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frequencyBox = QtWidgets.QGroupBox(self.centralwidget)
        self.frequencyBox.setMaximumSize(QtCore.QSize(261, 16777215))
        self.frequencyBox.setObjectName("frequencyBox")
        self.gridLayout = QtWidgets.QGridLayout(self.frequencyBox)
        self.gridLayout.setObjectName("gridLayout")
        self.stopFrequencyLabel = QtWidgets.QLabel(self.frequencyBox)
        self.stopFrequencyLabel.setObjectName("stopFrequencyLabel")
        self.gridLayout.addWidget(self.stopFrequencyLabel, 1, 0, 1, 1)
        self.stopFreq = QtWidgets.QDoubleSpinBox(self.frequencyBox)
        self.stopFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.stopFreq.setDecimals(0)
        self.stopFreq.setMinimum(1.0)
        self.stopFreq.setMaximum(10000000.0)
        self.stopFreq.setProperty("value", 10.0)
        self.stopFreq.setObjectName("stopFreq")
        self.gridLayout.addWidget(self.stopFreq, 1, 1, 1, 1)
        self.startFreq = QtWidgets.QDoubleSpinBox(self.frequencyBox)
        self.startFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.startFreq.setDecimals(0)
        self.startFreq.setMinimum(20.0)
        self.startFreq.setMaximum(10000000.0)
        self.startFreq.setProperty("value", 20.0)
        self.startFreq.setObjectName("startFreq")
        self.gridLayout.addWidget(self.startFreq, 0, 1, 1, 1)
        self.startFrequencyLabel = QtWidgets.QLabel(self.frequencyBox)
        self.startFrequencyLabel.setObjectName("startFrequencyLabel")
        self.gridLayout.addWidget(self.startFrequencyLabel, 0, 0, 1, 1)
        self.startFreqUnit = QtWidgets.QComboBox(self.frequencyBox)
        self.startFreqUnit.setObjectName("startFreqUnit")
        self.startFreqUnit.addItem("")
        self.startFreqUnit.addItem("")
        self.gridLayout.addWidget(self.startFreqUnit, 0, 2, 1, 1)
        self.stopFreqUnit = QtWidgets.QComboBox(self.frequencyBox)
        self.stopFreqUnit.setObjectName("stopFreqUnit")
        self.stopFreqUnit.addItem("")
        self.stopFreqUnit.addItem("")
        self.gridLayout.addWidget(self.stopFreqUnit, 1, 2, 1, 1)
        self.npoints = QtWidgets.QSpinBox(self.frequencyBox)
        self.npoints.setAlignment(QtCore.Qt.AlignCenter)
        self.npoints.setMinimum(1)
        self.npoints.setMaximum(500)
        self.npoints.setProperty("value", 20)
        self.npoints.setObjectName("npoints")
        self.gridLayout.addWidget(self.npoints, 2, 2, 1, 1)
        self.spacingType = QtWidgets.QComboBox(self.frequencyBox)
        self.spacingType.setObjectName("spacingType")
        self.spacingType.addItem("")
        self.spacingType.addItem("")
        self.spacingType.addItem("")
        self.gridLayout.addWidget(self.spacingType, 3, 2, 1, 1)
        self.pointsLabel = QtWidgets.QLabel(self.frequencyBox)
        self.pointsLabel.setObjectName("pointsLabel")
        self.gridLayout.addWidget(self.pointsLabel, 2, 0, 1, 2)
        self.pointSpacingLabel = QtWidgets.QLabel(self.frequencyBox)
        self.pointSpacingLabel.setObjectName("pointSpacingLabel")
        self.gridLayout.addWidget(self.pointSpacingLabel, 3, 0, 1, 2)
        self.gridLayout_6.addWidget(self.frequencyBox, 0, 0, 1, 1)
        self.displayControlBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayControlBox.sizePolicy().hasHeightForWidth())
        self.displayControlBox.setSizePolicy(sizePolicy)
        self.displayControlBox.setMinimumSize(QtCore.QSize(120, 0))
        self.displayControlBox.setMaximumSize(QtCore.QSize(95, 16777215))
        self.displayControlBox.setTitle("")
        self.displayControlBox.setObjectName("displayControlBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.displayControlBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.xaxisBox = QtWidgets.QGroupBox(self.displayControlBox)
        self.xaxisBox.setMinimumSize(QtCore.QSize(0, 0))
        self.xaxisBox.setObjectName("xaxisBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.xaxisBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.xaxisTemp = QtWidgets.QPushButton(self.xaxisBox)
        self.xaxisTemp.setObjectName("xaxisTemp")
        self.verticalLayout_4.addWidget(self.xaxisTemp)
        self.xaxisFreq = QtWidgets.QPushButton(self.xaxisBox)
        self.xaxisFreq.setObjectName("xaxisFreq")
        self.verticalLayout_4.addWidget(self.xaxisFreq)
        self.verticalLayout.addWidget(self.xaxisBox)
        self.yaxisBox = QtWidgets.QGroupBox(self.displayControlBox)
        self.yaxisBox.setMinimumSize(QtCore.QSize(0, 0))
        self.yaxisBox.setObjectName("yaxisBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.yaxisBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.impedanceButton = QtWidgets.QPushButton(self.yaxisBox)
        self.impedanceButton.setCheckable(True)
        self.impedanceButton.setObjectName("impedanceButton")
        self.verticalLayout_3.addWidget(self.impedanceButton)
        self.capacitanceButton = QtWidgets.QPushButton(self.yaxisBox)
        self.capacitanceButton.setCheckable(True)
        self.capacitanceButton.setObjectName("capacitanceButton")
        self.verticalLayout_3.addWidget(self.capacitanceButton)
        self.resistanceButton = QtWidgets.QPushButton(self.yaxisBox)
        self.resistanceButton.setCheckable(True)
        self.resistanceButton.setObjectName("resistanceButton")
        self.verticalLayout_3.addWidget(self.resistanceButton)
        self.inductanceButton = QtWidgets.QPushButton(self.yaxisBox)
        self.inductanceButton.setCheckable(True)
        self.inductanceButton.setObjectName("inductanceButton")
        self.verticalLayout_3.addWidget(self.inductanceButton)
        self.verticalLayout.addWidget(self.yaxisBox)
        self.scaleBox = QtWidgets.QGroupBox(self.displayControlBox)
        self.scaleBox.setMinimumSize(QtCore.QSize(0, 0))
        self.scaleBox.setObjectName("scaleBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scaleBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.autoScaleButton = QtWidgets.QPushButton(self.scaleBox)
        self.autoScaleButton.setCheckable(True)
        self.autoScaleButton.setObjectName("autoScaleButton")
        self.verticalLayout_2.addWidget(self.autoScaleButton)
        self.xaxisScale = QtWidgets.QComboBox(self.scaleBox)
        self.xaxisScale.setObjectName("xaxisScale")
        self.xaxisScale.addItem("")
        self.xaxisScale.addItem("")
        self.xaxisScale.addItem("")
        self.xaxisScale.addItem("")
        self.xaxisScale.addItem("")
        self.xaxisScale.setItemText(4, "")
        self.verticalLayout_2.addWidget(self.xaxisScale)
        self.yaxisScale = QtWidgets.QComboBox(self.scaleBox)
        self.yaxisScale.setObjectName("yaxisScale")
        self.yaxisScale.addItem("")
        self.yaxisScale.addItem("")
        self.yaxisScale.addItem("")
        self.yaxisScale.addItem("")
        self.verticalLayout_2.addWidget(self.yaxisScale)
        self.verticalLayout.addWidget(self.scaleBox)
        self.gridLayout_6.addWidget(self.displayControlBox, 0, 1, 2, 1)
        self.ImpdPlot = PlotWidget(self.centralwidget)
        self.ImpdPlot.setMinimumSize(QtCore.QSize(611, 671))
        self.ImpdPlot.setObjectName("ImpdPlot")
        self.gridLayout_6.addWidget(self.ImpdPlot, 0, 2, 5, 1)
        self.temperatureBox = QtWidgets.QGroupBox(self.centralwidget)
        self.temperatureBox.setMaximumSize(QtCore.QSize(261, 300))
        self.temperatureBox.setCheckable(True)
        self.temperatureBox.setObjectName("temperatureBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.temperatureBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tempControllerLabel = QtWidgets.QLabel(self.temperatureBox)
        self.tempControllerLabel.setObjectName("tempControllerLabel")
        self.gridLayout_2.addWidget(self.tempControllerLabel, 0, 0, 1, 1)
        self.inst = QtWidgets.QComboBox(self.temperatureBox)
        self.inst.setObjectName("inst")
        self.inst.addItem("")
        self.inst.addItem("")
        self.gridLayout_2.addWidget(self.inst, 0, 1, 1, 1)
        self.startTemperatureLabel = QtWidgets.QLabel(self.temperatureBox)
        self.startTemperatureLabel.setObjectName("startTemperatureLabel")
        self.gridLayout_2.addWidget(self.startTemperatureLabel, 1, 0, 1, 1)
        self.startTemp = QtWidgets.QDoubleSpinBox(self.temperatureBox)
        self.startTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.startTemp.setMinimum(10.0)
        self.startTemp.setMaximum(600.0)
        self.startTemp.setProperty("value", 300.0)
        self.startTemp.setObjectName("startTemp")
        self.gridLayout_2.addWidget(self.startTemp, 1, 1, 1, 1)
        self.stopTemperatureLabel = QtWidgets.QLabel(self.temperatureBox)
        self.stopTemperatureLabel.setObjectName("stopTemperatureLabel")
        self.gridLayout_2.addWidget(self.stopTemperatureLabel, 2, 0, 1, 1)
        self.stopTemp = QtWidgets.QDoubleSpinBox(self.temperatureBox)
        self.stopTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.stopTemp.setMinimum(10.0)
        self.stopTemp.setMaximum(600.0)
        self.stopTemp.setObjectName("stopTemp")
        self.gridLayout_2.addWidget(self.stopTemp, 2, 1, 1, 1)
        self.modeLabel = QtWidgets.QLabel(self.temperatureBox)
        self.modeLabel.setObjectName("modeLabel")
        self.gridLayout_2.addWidget(self.modeLabel, 3, 0, 1, 1)
        self.measureMode = QtWidgets.QComboBox(self.temperatureBox)
        self.measureMode.setObjectName("measureMode")
        self.measureMode.addItem("")
        self.measureMode.addItem("")
        self.measureMode.addItem("")
        self.gridLayout_2.addWidget(self.measureMode, 3, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.temperatureBox)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.measureLabel = QtWidgets.QLabel(self.frame)
        self.measureLabel.setObjectName("measureLabel")
        self.horizontalLayout.addWidget(self.measureLabel)
        self.tempInterval = QtWidgets.QSpinBox(self.frame)
        self.tempInterval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempInterval.setMinimum(1)
        self.tempInterval.setMaximum(100)
        self.tempInterval.setProperty("value", 5)
        self.tempInterval.setObjectName("tempInterval")
        self.horizontalLayout.addWidget(self.tempInterval)
        self.degreesLabel = QtWidgets.QLabel(self.frame)
        self.degreesLabel.setObjectName("degreesLabel")
        self.horizontalLayout.addWidget(self.degreesLabel)
        self.gridLayout_2.addWidget(self.frame, 4, 0, 1, 2)
        self.loadTempButton = QtWidgets.QPushButton(self.temperatureBox)
        self.loadTempButton.setObjectName("loadTempButton")
        self.gridLayout_2.addWidget(self.loadTempButton, 5, 0, 1, 2)
        self.gridLayout_6.addWidget(self.temperatureBox, 1, 0, 2, 1)
        self.measureControlBox = QtWidgets.QGroupBox(self.centralwidget)
        self.measureControlBox.setMinimumSize(QtCore.QSize(120, 0))
        self.measureControlBox.setMaximumSize(QtCore.QSize(120, 120))
        self.measureControlBox.setObjectName("measureControlBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.measureControlBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.startButton = QtWidgets.QPushButton(self.measureControlBox)
        self.startButton.setMinimumSize(QtCore.QSize(0, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.startButton.setPalette(palette)
        self.startButton.setStyleSheet("background-color: rgb(230, 255, 254)")
        self.startButton.setObjectName("startButton")
        self.gridLayout_4.addWidget(self.startButton, 0, 1, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.measureControlBox)
        self.stopButton.setMinimumSize(QtCore.QSize(0, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.stopButton.setPalette(palette)
        self.stopButton.setStyleSheet("background-color: rgb(255, 231, 210)")
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_4.addWidget(self.stopButton, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.measureControlBox, 2, 1, 2, 1)
        self.fileBox = QtWidgets.QGroupBox(self.centralwidget)
        self.fileBox.setMaximumSize(QtCore.QSize(261, 16777215))
        self.fileBox.setObjectName("fileBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fileBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.saveParamButton = QtWidgets.QPushButton(self.fileBox)
        self.saveParamButton.setObjectName("saveParamButton")
        self.gridLayout_3.addWidget(self.saveParamButton, 1, 1, 1, 1)
        self.loadParamButton = QtWidgets.QPushButton(self.fileBox)
        self.loadParamButton.setObjectName("loadParamButton")
        self.gridLayout_3.addWidget(self.loadParamButton, 1, 0, 1, 1)
        self.filenameText = QtWidgets.QLineEdit(self.fileBox)
        self.filenameText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filenameText.setObjectName("filenameText")
        self.gridLayout_3.addWidget(self.filenameText, 0, 1, 1, 1)
        self.saveFilenameLabel = QtWidgets.QLabel(self.fileBox)
        self.saveFilenameLabel.setObjectName("saveFilenameLabel")
        self.gridLayout_3.addWidget(self.saveFilenameLabel, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.fileBox, 3, 0, 1, 1)
        self.statusBox = QtWidgets.QGroupBox(self.centralwidget)
        self.statusBox.setMaximumSize(QtCore.QSize(390, 16777215))
        self.statusBox.setObjectName("statusBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.statusBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.temperatureStatusLabel = QtWidgets.QLabel(self.statusBox)
        self.temperatureStatusLabel.setObjectName("temperatureStatusLabel")
        self.gridLayout_5.addWidget(self.temperatureStatusLabel, 0, 4, 1, 1)
        self.impedanceReStatusLabel = QtWidgets.QLabel(self.statusBox)
        self.impedanceReStatusLabel.setObjectName("impedanceReStatusLabel")
        self.gridLayout_5.addWidget(self.impedanceReStatusLabel, 1, 0, 1, 1)
        self.frequencyStatusLabel = QtWidgets.QLabel(self.statusBox)
        self.frequencyStatusLabel.setObjectName("frequencyStatusLabel")
        self.gridLayout_5.addWidget(self.frequencyStatusLabel, 0, 0, 1, 1)
        self.impedanceImStatusLabel = QtWidgets.QLabel(self.statusBox)
        self.impedanceImStatusLabel.setObjectName("impedanceImStatusLabel")
        self.gridLayout_5.addWidget(self.impedanceImStatusLabel, 1, 4, 1, 1)
        self.capacitanceStatusLabel = QtWidgets.QLabel(self.statusBox)
        self.capacitanceStatusLabel.setObjectName("capacitanceStatusLabel")
        self.gridLayout_5.addWidget(self.capacitanceStatusLabel, 2, 0, 1, 1)
        self.tandstatusLabel = QtWidgets.QLabel(self.statusBox)
        self.tandstatusLabel.setObjectName("tandstatusLabel")
        self.gridLayout_5.addWidget(self.tandstatusLabel, 2, 4, 1, 1)
        self.tandStatus = QtWidgets.QLineEdit(self.statusBox)
        self.tandStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.tandStatus.setPalette(palette)
        self.tandStatus.setStyleSheet("font: 11pt;")
        self.tandStatus.setObjectName("tandStatus")
        self.gridLayout_5.addWidget(self.tandStatus, 2, 5, 1, 1)
        self.capStatus = QtWidgets.QLineEdit(self.statusBox)
        self.capStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.capStatus.setPalette(palette)
        self.capStatus.setStyleSheet("font: 11pt;")
        self.capStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.capStatus.setObjectName("capStatus")
        self.gridLayout_5.addWidget(self.capStatus, 2, 1, 1, 1)
        self.tempStatus = QtWidgets.QLineEdit(self.statusBox)
        self.tempStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.tempStatus.setPalette(palette)
        self.tempStatus.setStyleSheet("font: 11pt;")
        self.tempStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempStatus.setObjectName("tempStatus")
        self.gridLayout_5.addWidget(self.tempStatus, 0, 5, 1, 1)
        self.ZImStatus = QtWidgets.QLineEdit(self.statusBox)
        self.ZImStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.ZImStatus.setPalette(palette)
        self.ZImStatus.setStyleSheet("font: 11pt;")
        self.ZImStatus.setObjectName("ZImStatus")
        self.gridLayout_5.addWidget(self.ZImStatus, 1, 5, 1, 1)
        self.ZReStatus = QtWidgets.QLineEdit(self.statusBox)
        self.ZReStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.ZReStatus.setPalette(palette)
        self.ZReStatus.setStyleSheet("font: 11pt;")
        self.ZReStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ZReStatus.setObjectName("ZReStatus")
        self.gridLayout_5.addWidget(self.ZReStatus, 1, 1, 1, 1)
        self.freqStatus = QtWidgets.QLineEdit(self.statusBox)
        self.freqStatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.freqStatus.setPalette(palette)
        self.freqStatus.setStyleSheet("font: 11pt;")
        self.freqStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.freqStatus.setObjectName("freqStatus")
        self.gridLayout_5.addWidget(self.freqStatus, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.statusBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 0, 3, 3, 1)
        self.sampleIDLabel = QtWidgets.QLabel(self.statusBox)
        self.sampleIDLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleIDLabel.setObjectName("sampleIDLabel")
        self.gridLayout_5.addWidget(self.sampleIDLabel, 3, 0, 1, 2)
        self.sampleStatusLabel = QtWidgets.QLabel(self.statusBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 115, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 115, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.sampleStatusLabel.setPalette(palette)
        self.sampleStatusLabel.setObjectName("sampleStatusLabel")
        self.gridLayout_5.addWidget(self.sampleStatusLabel, 3, 4, 1, 2)
        self.gridLayout_6.addWidget(self.statusBox, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1119, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdvance_Measurement_Settings = QtWidgets.QAction(MainWindow)
        self.actionAdvance_Measurement_Settings.setObjectName("actionAdvance_Measurement_Settings")
        self.menuOptions.addAction(self.actionAdvance_Measurement_Settings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.stopFreqUnit.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Impedance Measurement"))
        self.frequencyBox.setTitle(_translate("MainWindow", "Frequency"))
        self.stopFrequencyLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Stop</span></p></body></html>"))
        self.startFrequencyLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Start</span></p></body></html>"))
        self.startFreqUnit.setItemText(0, _translate("MainWindow", "Hz"))
        self.startFreqUnit.setItemText(1, _translate("MainWindow", "MHz"))
        self.stopFreqUnit.setItemText(0, _translate("MainWindow", "Hz"))
        self.stopFreqUnit.setItemText(1, _translate("MainWindow", "MHz"))
        self.spacingType.setItemText(0, _translate("MainWindow", "Linear"))
        self.spacingType.setItemText(1, _translate("MainWindow", "Logarithm"))
        self.spacingType.setItemText(2, _translate("MainWindow", "Linear-Log"))
        self.pointsLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Number of points</span></p></body></html>"))
        self.pointSpacingLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Point spacing</span></p></body></html>"))
        self.xaxisBox.setTitle(_translate("MainWindow", "X-Axis"))
        self.xaxisTemp.setText(_translate("MainWindow", "Temperature"))
        self.xaxisFreq.setText(_translate("MainWindow", "Frequency"))
        self.yaxisBox.setTitle(_translate("MainWindow", "Y-Axis"))
        self.impedanceButton.setText(_translate("MainWindow", "Impedance"))
        self.capacitanceButton.setText(_translate("MainWindow", "Capacitance"))
        self.resistanceButton.setText(_translate("MainWindow", "Resistance"))
        self.inductanceButton.setText(_translate("MainWindow", "Inductance"))
        self.scaleBox.setTitle(_translate("MainWindow", "Scale"))
        self.autoScaleButton.setText(_translate("MainWindow", "Auto"))
        self.xaxisScale.setItemText(0, _translate("MainWindow", "X Axis"))
        self.xaxisScale.setItemText(1, _translate("MainWindow", "Linear"))
        self.xaxisScale.setItemText(2, _translate("MainWindow", "Log (abs)"))
        self.xaxisScale.setItemText(3, _translate("MainWindow", "Log (base 10)"))
        self.yaxisScale.setItemText(0, _translate("MainWindow", "Y Axis"))
        self.yaxisScale.setItemText(1, _translate("MainWindow", "Linear"))
        self.yaxisScale.setItemText(2, _translate("MainWindow", "Log (abs)"))
        self.yaxisScale.setItemText(3, _translate("MainWindow", "Log (base 10)"))
        self.temperatureBox.setTitle(_translate("MainWindow", "Temperature"))
        self.tempControllerLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Controller</span></p></body></html>"))
        self.inst.setItemText(0, _translate("MainWindow", "Chino"))
        self.inst.setItemText(1, _translate("MainWindow", "Linkam"))
        self.startTemperatureLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Start (K)</span></p></body></html>"))
        self.stopTemperatureLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Stop (K)</span></p></body></html>"))
        self.modeLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Mode</span></p></body></html>"))
        self.measureMode.setItemText(0, _translate("MainWindow", "Continuous"))
        self.measureMode.setItemText(1, _translate("MainWindow", "Specify Interval"))
        self.measureMode.setItemText(2, _translate("MainWindow", "Load from file"))
        self.measureLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Measure every</span></p></body></html>"))
        self.degreesLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">degrees</span></p></body></html>"))
        self.loadTempButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Text file containing one temperature (°C) point in each line, no other text. Preferably in ascending or descending order, but not necessary.</span></p></body></html>"))
        self.loadTempButton.setText(_translate("MainWindow", "Load temperature list from file"))
        self.measureControlBox.setTitle(_translate("MainWindow", "Measurement"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.fileBox.setTitle(_translate("MainWindow", "File"))
        self.saveParamButton.setText(_translate("MainWindow", "Save Parameters"))
        self.loadParamButton.setText(_translate("MainWindow", "Load Parameters"))
        self.filenameText.setText(_translate("MainWindow", "sample1.csv"))
        self.saveFilenameLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Save Filename</span></p></body></html>"))
        self.statusBox.setTitle(_translate("MainWindow", "Current Status"))
        self.temperatureStatusLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Temperature</span></p></body></html>"))
        self.impedanceReStatusLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Z\' (Re)</span></p></body></html>"))
        self.frequencyStatusLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Frequency</span></p></body></html>"))
        self.impedanceImStatusLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Z\'\' (Im)</span></p></body></html>"))
        self.capacitanceStatusLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Capacitance</span></p></body></html>"))
        self.tandstatusLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">tan(δ)</span></p></body></html>"))
        self.capStatus.setText(_translate("MainWindow", "F"))
        self.tempStatus.setText(_translate("MainWindow", "°C"))
        self.ZReStatus.setText(_translate("MainWindow", "Ω"))
        self.freqStatus.setText(_translate("MainWindow", "Hz"))
        self.sampleIDLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Sample ID:</span></p></body></html>"))
        self.sampleStatusLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">CryoChamber 1</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionAdvance_Measurement_Settings.setText(_translate("MainWindow", "Advance Measurement Settings"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

